# This is a basic workflow that is manually triggered

name: getting data test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
