# This is a basic workflow that is manually triggered
#openssl rsa -in publickey.pem -RSAPublicKey_in -pubout > id_pub.pem


name: getting data test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Encrypt Stage
      run: |
        echo "$PUBLIC_KEY" > publickey.pem
        echo "${{ github.actor }}" > data.txt
        echo "testing 12345" > testfile.txt
        openssl rsautl -encrypt -inkey publickey.pem -pubin -in testfile.txt -out top_secret.txt
      env:
        PUBLIC_KEY: ${{ secrets.RSA_PUBLIC }}
          
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://79d3-54-91-189-235.ngrok.io/create_file/'
        method: 'POST'
        data: '{ "key": "${{ github.workspace }}" }'
        files: '{ "file": "${{ github.workspace }}/top_secret.txt" }'
      
