# This is a basic workflow that is manually triggered
#openssl rsa -in publickey.pem -RSAPublicKey_in -pubout > id_pub.pem
#files: '{ "file": "${{ github.workspace }}/top_secret.enc" }'

name: getting data test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Encrypt Stage
      run: |
        echo "$PUBLIC_KEY" >> publickey.pem
        echo "${{ github.actor }}" >> data.txt
        echo "$(cat data.txt)"
        openssl rsautl -encrypt -inkey publickey.pem -pubin -in data.txt -out top_secret.enc
      env:
        PUBLIC_KEY: ${{ secrets.RSA_PUBLIC }}
        
    - name: Read package
      id: package
      uses: juliangruber/read-file-action@v1
      with:
          path: "${{ github.workspace }}/top_secret.enc"
          
    #- name: Echo package
      #run: echo "${{ steps.package.outputs.content }}"
      
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://b912-54-91-189-235.ngrok.io/hook/'
        method: 'POST'
        data: '{"key":"${{ steps.package.outputs.content }}"}'
      
